### ISSUE TITLE
`inputs` and `images` are backwards?

### ISSUE THREAD

**Issue by Makeshift** [Noelware/docker-manifest-action#163]
According to the README, `inputs` should be the final name of your images (IE the things that are `docker manifest push`'d, and `images` should be the list of images that you're merging to create the inputs.

But when running the action, it appears they're the other way around. Given the following input:
```
- uses: Noelware/docker-manifest-action@v0.3.1
  with:
    inputs: test:master
    images: test:77762fb4d2eb086d2bc806c3aaa9f35db2f08801-x64,test:77762fb4d2eb086d2bc806c3aaa9f35db2f08801-arm64
```

it works correctly, which is the opposite of what the Readme says.

```
Images to Merge => test:ea656058259dade7f6d2f4cd290b45ae74a44ae5-x64, test:ea656058259dade7f6d2f4cd290b45ae74a44ae5-arm64
  Base Images     => test:master
  Amend?          => No
  Push?           => Yes
Creating manifest for image [test:master] with [test:ea656058259dade7f6d2f4cd290b45ae74a44ae5-x64, test:ea656058259dade7f6d2f4cd290b45ae74a44ae5-arm64] outputs
/usr/bin/docker manifest create test:master test:ea656058259dade7f6d2f4cd290b45ae74a44ae5-x64 test:ea656058259dade7f6d2f4cd290b45ae74a44ae5-arm64

```

Also, there are several references to an `outputs` input which doesn't exist.
