### ISSUE TITLE
Error: Unable to resolve action `noelware/docker-manifest-action@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by bubenkoff** [Noelware/docker-manifest-action#824]
Using it as per the docs, but failing with the version not found:

```
        uses: Noelware/docker-manifest-action@v1 # or use whatever version.
        with:
          inputs: ${{ env.IMAGE_URL }}
          images: ${{ env.EXTRA_IMAGE_URLS }}
          push: true
```
Should I use master instead?
